---
driver:
  name: gce
  project: dazzlingwrench
  region: us-east1
  preemptible: true
  metadata:
    ssh-keys: <%= 'kitchenuser:' + IO.binread("/tmp/id_rsa.pub").rstrip! %>
  tags:
  - fxinnovation

provisioner:
  name: chef_zero
  max_retries: 3
  wait_for_retry: 90
  retry_on_exit_code:
  - 35
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec
  sudo: true
  format: junit
  output: "%{platform}_%{suite}_inspec.xml"

transport:
  username: kitchenuser
  ssh_key: /tmp/id_rsa

platforms:
  - name: centos6
    driver:
      image_project: centos-cloud
      image_family: centos-6
  - name: centos7
    driver:
      image_project: centos-cloud
      image_family: centos-7
  - name: redhat6
    driver:
      image_project: rhel-cloud
      image_family: rhel-6
  - name: redhat7
    driver:
      image_project: rhel-cloud
      image_family: rhel-7
  - name: ubuntu1404
    driver:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1404-lts
  - name: ubuntu1604
    driver:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1604-lts
  - name: debian8
    driver:
      image_project: debian-cloud
      image_family: debian-8
  - name: debian9
    driver:
      image_project: debian-cloud
      image_family: debian-9

suites:
  - name: linux
    run_list:
      - recipe[pam_fx::kitchen]
    attributes:
      pam_fx:
        name: 'pam-test'
        lines:
          - { 'mechanism': 'auth', 'flag': 'required', 'module': 'pam_wheel.so', 'arguments': 'use_uid'}
          - { 'mechanism': 'auth', 'flag': 'required', 'module': 'pam_wheel.so' }
    includes:
    - centos6
    - centos7
    - redhat6
    - redhat7
    - debian8
    - debian9
    - ubuntu1604
    verifier:
      inspec_tests:
      - name: linux
        path: test/integration/linux
